services:
  - type: web
    name: mw-render-relay
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT --timeout 60 app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
